/**
 * Registry-based Scanner — Compile-time Module Scanner
 *
 * Alternative scanner that uses the virtual module registries generated by
 * @stackra/vite-decorator-discovery instead of runtime reflection.
 *
 * This scanner provides:
 * - Zero runtime overhead (no reflect-metadata)
 * - Faster bootstrap (pre-compiled metadata)
 * - Static validation at build time
 * - Smaller bundle size (no reflection polyfill)
 *
 * ## Usage:
 *
 * ```typescript
 * import { RegistryScanner } from '@stackra/ts-container';
 *
 * const container = new ModuleContainer();
 * const scanner = new RegistryScanner(container);
 * await scanner.scan(AppModule);
 * ```
 *
 * ## Requirements:
 *
 * 1. Add @stackra/vite-decorator-discovery to your vite.config.ts
 * 2. Add type reference to vite-env.d.ts
 * 3. Use RegistryScanner instead of DependenciesScanner
 *
 * @module injector/registry-scanner
 */

import type { Type, DynamicModule, Provider, ForwardReference } from '@/interfaces';
import type { RegistryModuleMetadata } from '@/interfaces/registry-module-metadata.interface';
import type { RegistryProviderMetadata } from '@/interfaces/registry-provider-metadata.interface';
import type { ModuleContainer } from './container';

/**
 * Lazy-loaded virtual module registries.
 * These are loaded on first use to avoid top-level await.
 */
let MODULE_REGISTRY: any[] | undefined;
let PROVIDER_REGISTRY: any[] | undefined;
let registriesLoaded = false;
let registriesLoadError: Error | undefined;

/**
 * Load virtual module registries.
 * This is called lazily on first scan() to avoid top-level await.
 */
async function loadRegistries(): Promise<void> {
  if (registriesLoaded) {
    return;
  }

  try {
    // @ts-expect-error — virtual module may not exist at build time
    const modulesModule = await import('virtual:decorator-registry/modules');
    MODULE_REGISTRY = modulesModule.MODULE_REGISTRY;

    // @ts-expect-error — virtual module may not exist at build time
    const providersModule = await import('virtual:decorator-registry/providers');
    PROVIDER_REGISTRY = providersModule.PROVIDER_REGISTRY;

    registriesLoaded = true;
  } catch (error) {
    registriesLoadError = error instanceof Error ? error : new Error(String(error));
    registriesLoaded = true; // Mark as loaded even on error to avoid retrying
  }
}

/**
 * Scans the module tree using pre-compiled registries from the decorator discovery plugin.
 *
 * This is a drop-in replacement for `DependenciesScanner` that uses compile-time
 * metadata instead of runtime reflection.
 *
 * @example
 * ```typescript
 * const container = new ModuleContainer();
 * const scanner = new RegistryScanner(container);
 * await scanner.scan(AppModule);
 * ```
 */
export class RegistryScanner {
  /** Cache of module registry entries keyed by class name. */
  private moduleCache = new Map<string, RegistryModuleMetadata>();

  /** Cache of provider registry entries keyed by class name. */
  private providerCache = new Map<string, RegistryProviderMetadata>();

  /**
   * Create a new RegistryScanner.
   *
   * @param container - The `ModuleContainer` to populate with modules and providers
   */
  constructor(private readonly container: ModuleContainer) {
    this.buildCaches();
  }

  /**
   * Build lookup caches from the registries.
   */
  private buildCaches(): void {
    if (!MODULE_REGISTRY || !PROVIDER_REGISTRY) {
      return;
    }

    for (const module of MODULE_REGISTRY) {
      this.moduleCache.set(module.className, module);
    }

    for (const provider of PROVIDER_REGISTRY) {
      this.providerCache.set(provider.className, provider);
    }
  }

  /**
   * Scan the entire module tree starting from the root module.
   *
   * Uses pre-compiled metadata from virtual registries instead of reflect-metadata.
   *
   * @param rootModule - The root module class (your AppModule)
   * @returns A Promise that resolves when scanning is complete
   *
   * @throws Error if virtual registries are not available
   * @throws Error if root module is not found in registry
   *
   * @example
   * ```typescript
   * const scanner = new RegistryScanner(container);
   * await scanner.scan(AppModule);
   * ```
   */
  public async scan(rootModule: Type<any>): Promise<void> {
    // Load virtual registries (lazy-loaded to avoid top-level await)
    await loadRegistries();

    // Check if registries are available
    if (registriesLoadError || !MODULE_REGISTRY || !PROVIDER_REGISTRY) {
      throw new Error(
        'Virtual decorator registries not found. ' +
          'Make sure @stackra/vite-decorator-discovery plugin is enabled in vite.config.ts. ' +
          'Alternatively, use DependenciesScanner for runtime reflection.'
      );
    }

    // Rebuild caches after loading
    this.buildCaches();

    // Find root module in registry
    const rootModuleName = rootModule.name;
    const rootMetadata = this.moduleCache.get(rootModuleName);

    if (!rootMetadata) {
      throw new Error(
        `Module "${rootModuleName}" not found in decorator registry. ` +
          'Make sure the module is decorated with @Module() and the decorator discovery plugin is enabled.'
      );
    }

    // Phase 1: Discover all modules (recursive DFS)
    await this.scanForModules(rootModule, rootMetadata, []);

    // Phase 2: Register providers, imports, exports for each module
    await this.scanModulesForDependencies();

    // Phase 3: Link global modules to all other modules
    this.container.bindGlobalScope();
  }

  // ── Phase 1: Module discovery ────────────────────────────────────────────

  /**
   * Recursively discover and register all modules in the graph.
   *
   * Uses pre-compiled metadata from the registry instead of reflect-metadata.
   * Tracks module distance from root for lifecycle hook ordering.
   *
   * @param moduleClass - The module class
   * @param metadata - The module's metadata from the registry
   * @param ctxRegistry - Already-visited modules (for cycle detection)
   * @param distance - Distance from root module (0 = root, 1 = direct import, etc.)
   */
  private async scanForModules(
    moduleClass: Type<any>,
    metadata: RegistryModuleMetadata,
    ctxRegistry: string[],
    distance: number = 0
  ): Promise<void> {
    const moduleName = moduleClass.name;

    // Skip if already visited (circular import protection)
    if (ctxRegistry.includes(moduleName)) return;
    ctxRegistry.push(moduleName);

    // Register this module in the container
    const { moduleRef } = await this.container.addModule(moduleClass);

    // Set module distance for lifecycle hook ordering
    moduleRef.distance = distance;

    // Get this module's imports from metadata
    const imports = this.getModuleImports(metadata);

    // Recurse into each import with distance + 1
    for (const importDef of imports) {
      const importClass = this.resolveImport(importDef);
      if (!importClass) continue;

      const importName = importClass.name;
      const importMetadata = this.moduleCache.get(importName);

      if (!importMetadata) {
        throw new Error(
          `Module "${moduleName}" imports "${importName}" which is not found in the registry. ` +
            'Make sure all imported modules are decorated with @Module().'
        );
      }

      await this.scanForModules(importClass, importMetadata, ctxRegistry, distance + 1);
    }
  }

  // ── Phase 2: Dependency registration ─────────────────────────────────────

  /**
   * For each registered module, read its metadata and register
   * providers, imports, and exports in the container.
   */
  private async scanModulesForDependencies(): Promise<void> {
    const modules = this.container.getModules();

    for (const [token, moduleRef] of modules) {
      const metadata = this.moduleCache.get(moduleRef.metatype.name);
      if (!metadata) continue;

      // Register imports (module relationships)
      await this.reflectImports(moduleRef.metatype, metadata, token);

      // Register providers
      this.reflectProviders(moduleRef.metatype, metadata, token);

      // Register exports
      this.reflectExports(moduleRef.metatype, metadata, token);
    }
  }

  /**
   * Read and register a module's imports from registry metadata.
   */
  private async reflectImports(
    _metatype: Type<any>,
    metadata: RegistryModuleMetadata,
    token: string
  ): Promise<void> {
    const imports = this.getModuleImports(metadata);

    for (const importDef of imports) {
      const resolved = this.resolveImport(importDef);
      if (resolved) {
        this.container.addImport(resolved, token);
      }
    }
  }

  /**
   * Read and register a module's providers from registry metadata.
   */
  private reflectProviders(
    _metatype: Type<any>,
    metadata: RegistryModuleMetadata,
    token: string
  ): void {
    const providers = this.getModuleProviders(metadata);

    for (const provider of providers) {
      this.container.addProvider(provider, token);
    }
  }

  /**
   * Read and register a module's exports from registry metadata.
   */
  private reflectExports(
    _metatype: Type<any>,
    metadata: RegistryModuleMetadata,
    token: string
  ): void {
    const exports = this.getModuleExports(metadata);

    for (const exported of exports) {
      this.container.addExport(exported, token);
    }
  }

  // ── Helpers ──────────────────────────────────────────────────────────────

  /**
   * Get a module's imports from registry metadata.
   */
  private getModuleImports(metadata: RegistryModuleMetadata): any[] {
    const args = metadata.args[0];
    if (typeof args === 'object' && args !== null && Array.isArray(args.imports)) {
      return args.imports;
    }
    return [];
  }

  /**
   * Get a module's providers from registry metadata.
   */
  private getModuleProviders(metadata: RegistryModuleMetadata): Provider[] {
    const args = metadata.args[0];
    if (typeof args === 'object' && args !== null && Array.isArray(args.providers)) {
      return args.providers;
    }
    return [];
  }

  /**
   * Get a module's exports from registry metadata.
   */
  private getModuleExports(metadata: RegistryModuleMetadata): any[] {
    const args = metadata.args[0];
    if (typeof args === 'object' && args !== null && Array.isArray(args.exports)) {
      return args.exports;
    }
    return [];
  }

  /**
   * Resolve an import definition to a class reference.
   *
   * Handles both direct class references and dynamic modules.
   */
  private resolveImport(importDef: any): Type<any> | null {
    // Handle dynamic modules
    if (this.isDynamicModule(importDef)) {
      return importDef.module;
    }

    // Handle forward references
    if (this.isForwardReference(importDef)) {
      return importDef.forwardRef();
    }

    // Direct class reference
    if (typeof importDef === 'function') {
      return importDef;
    }

    return null;
  }

  /**
   * Check if a value is a dynamic module.
   */
  private isDynamicModule(value: any): value is DynamicModule {
    return value && typeof value === 'object' && 'module' in value;
  }

  /**
   * Check if a value is a forward reference.
   */
  private isForwardReference(value: any): value is ForwardReference {
    return value && typeof value === 'object' && 'forwardRef' in value;
  }
}
