/**
 * RegistryModuleMetadata Interface
 *
 * Describes the shape of a module entry in the virtual decorator registry
 * generated by `@stackra-inc/vite-decorator-discovery` at compile time.
 *
 * This is distinct from {@link ModuleMetadata} (the `@Module()` decorator options).
 * `RegistryModuleMetadata` is the raw record stored in the pre-compiled registry,
 * containing the class name, file path, and raw decorator arguments.
 *
 * Used exclusively by {@link RegistryScanner} to look up module definitions
 * without runtime reflection.
 *
 * @module interfaces/registry-module-metadata
 */

/**
 * A module entry in the compile-time virtual decorator registry.
 *
 * Each `@Module()`-decorated class produces one of these records in the
 * `virtual:decorator-registry/modules` virtual module. The `RegistryScanner`
 * reads these records instead of using `reflect-metadata` at runtime.
 *
 * @example
 * ```typescript
 * // Generated by the vite-decorator-discovery plugin:
 * export const MODULE_REGISTRY: RegistryModuleMetadata[] = [
 *   {
 *     name: 'AppModule',
 *     className: 'AppModule',
 *     filePath: 'src/app.module.ts',
 *     args: [{ imports: [UserModule], providers: [AppService] }],
 *   },
 * ];
 * ```
 */
export interface RegistryModuleMetadata {
  /**
   * The display name of the module (typically the class name).
   */
  name: string;

  /**
   * The class name of the module, used as the lookup key in the registry cache.
   */
  className: string;

  /**
   * The source file path where the module class is defined.
   * Used for debugging and error messages.
   */
  filePath: string;

  /**
   * The raw arguments passed to the `@Module()` decorator.
   * `args[0]` is the `ModuleMetadata` object (imports, providers, exports).
   */
  args: any[];
}
