/**
 * RegistryProviderMetadata Interface
 *
 * Describes the shape of a provider entry in the virtual decorator registry
 * generated by `@stackra-inc/vite-decorator-discovery` at compile time.
 *
 * This is the compile-time counterpart to the runtime `InstanceWrapper`.
 * `RegistryProviderMetadata` is the raw record stored in the pre-compiled
 * registry, containing the class name, file path, and raw decorator arguments.
 *
 * Used exclusively by {@link RegistryScanner} to look up provider definitions
 * without runtime reflection.
 *
 * @module interfaces/registry-provider-metadata
 */

/**
 * A provider entry in the compile-time virtual decorator registry.
 *
 * Each `@Injectable()`-decorated class produces one of these records in the
 * `virtual:decorator-registry/providers` virtual module. The `RegistryScanner`
 * reads these records instead of using `reflect-metadata` at runtime.
 *
 * @example
 * ```typescript
 * // Generated by the vite-decorator-discovery plugin:
 * export const PROVIDER_REGISTRY: RegistryProviderMetadata[] = [
 *   {
 *     name: 'UserService',
 *     className: 'UserService',
 *     filePath: 'src/user/user.service.ts',
 *     args: [{ scope: Scope.DEFAULT }],
 *   },
 * ];
 * ```
 */
export interface RegistryProviderMetadata {
  /**
   * The display name of the provider (typically the class name).
   */
  name: string;

  /**
   * The class name of the provider, used as the lookup key in the registry cache.
   */
  className: string;

  /**
   * The source file path where the provider class is defined.
   * Used for debugging and error messages.
   */
  filePath: string;

  /**
   * The raw arguments passed to the `@Injectable()` decorator.
   * `args[0]` is the `ScopeOptions` object (if provided).
   */
  args: any[];
}
